---
title: "R Notebook"
output: html_notebook
---
```{r load-packages, message=FALSE, include=FALSE}
library(knitr)
library(tidyverse)
library(broom)
library(htmltools)
library(janitor)
library(kableExtra)
```



```{r}
Kneset25 <- read.csv("../data/Updated/Election_Res.csv")
Kneset24 <- read.csv("../data/Updated/kneset24.csv")
Kneset23 <- read.csv("../data/Updated/kneset23.csv")
Kneset22 <- read.csv("../data/Updated/kneset22.csv")
Kneset21 <- read.csv("../data/Updated/kneset21.csv")
Kneset20 <- read.csv("../data/Updated/kneset20.csv")
Properties_rooms <- read.csv("../data/Updated/properties_by_rooms.csv")
Purcheuses <- read.csv("../data/Updated/property_purchases.csv")
Vacant_apartments <- read.csv("../data/Updated/vacant_apartments.csv")
liable <- read.csv("../data/Updated/liable_for_public_housing_noMa.csv")


```
 
```{r}
Purcheuses <- Purcheuses %>% clean_names()
Purcheuses
```

 
```{r}
# liable 
Purcheuses[is.na(Purcheuses)] <- 0

# Purcheuses

Purcheuses_summarized <- Purcheuses %>%
  group_by(lamas_name,lamas_code) %>%
  summarize(
    sum_x3_rooms_apartments = sum(x3_rooms_apartments, na.rm = TRUE),
    sum_x4_rooms_apartments = sum(x4_rooms_apartments, na.rm = TRUE),
    average_price_nis_3_rooms_apartments = sum(average_price_nis_3_rooms_apartments, na.re = TRUE),
    average_price_nis_4_rooms_apartments = sum(average_price_nis_4_rooms_apartments, na.rm = TRUE)
  )

Purcheuses_summarized <- Purcheuses_summarized %>% 
  group_by(lamas_name,lamas_code) %>% 
  summarize(
    total_amount = sum(average_price_nis_3_rooms_apartments + average_price_nis_4_rooms_apartments, na.rm = TRUE),
    appartment_count = sum(sum_x3_rooms_apartments + sum_x4_rooms_apartments)
  )

Purcheuses_summarized$avg_price <- Purcheuses_summarized$total_amount/Purcheuses_summarized$appartment_count



# Purcheuses_summarized
# Purcheues_summary <- Purcheuses %>%
#   group_by(Lamas_code) %>%
#   summarise(total_apartments = sum(x3_rooms_apartments + x4_rooms_apartments))

Purcheuses_liable <- left_join(Purcheuses_summarized, liable, by = c( "lamas_code" = "lamas.code"))
Purcheuses_liable <- Purcheuses_liable %>%  drop_na()
Purcheuses_liable

lm_model <- lm(avg_price ~  familes.with.kids.allowance + Families.with.more.than.4.kids + people.with.general.disability + elederly + kids.with.disabilities,
data = Purcheuses_liable)
summary(lm_model)
```
```{r}
Purchuses_sum2<- Purcheuses %>%
  mutate(
    x3_average_paid_in_Mil = (x3_rooms_apartments * average_price_nis_3_rooms_apartments) / 1000000,
    x4_average_paid_in_Mil = (x4_rooms_apartments * average_price_nis_4_rooms_apartments) / 1000000,
    total_paid_in_Mil = x3_average_paid_in_Mil + x4_average_paid_in_Mil,
    sum_apartments = x3_rooms_apartments + x4_rooms_apartments
  )

Purchuses_sum2 <- Purchuses_sum2 %>% 
    group_by(lamas_name,lamas_code) %>%
  summarize(
    sum_x3_rooms_apartments = sum(x3_rooms_apartments, na.rm = TRUE),
    sum_x4_rooms_apartments = sum(x4_rooms_apartments, na.rm = TRUE)
  ) %>% 
  group_by(lamas_name,lamas_code) %>%
  summarize(
   apartment_count = sum( sum_x3_rooms_apartments + sum_x4_rooms_apartments)
  )

Purchuses_sum2

Purcheuses_sum2_liable <- left_join(Purchuses_sum2, liable, by = c( "lamas_code" = "lamas.code"))
lm_model <- lm(apartment_count ~  familes.with.kids.allowance + Families.with.more.than.4.kids + people.with.general.disability + elederly + kids.with.disabilities,
data = Purcheuses_sum2_liable)
summary(lm_model)
```
```{r}
pos_Apt_model <- glm(apartment_count ~familes.with.kids.allowance + Families.with.more.than.4.kids + people.with.general.disability + elederly + kids.with.disabilities,
data = Purcheuses_sum2_liable, family = poisson)
summary(pos_Apt_model)
```
```{r}
# Predicted values
predicted <- predict(pos_Apt_model, type = "response")

# Actual values
actual <- Purcheuses_sum2_liable$apartment_count

# Compute RMSE
rmse <- sqrt(mean((predicted - actual)^2))

# Compute MAE
mae <- mean(abs(predicted - actual))

# Compute SD of residuals
residuals <- actual - predicted
sd_resid <- sd(residuals)

# Print results
cat("RMSE:", rmse, "\n")
cat("MAE:", mae, "\n")
cat("SD of Residuals:", sd_resid, "\n")

```
```{r}
Socio <- read.csv("../data/Updated/Lamas cities and socio.csv")
Socio <- Socio %>% 
  clean_names()
Socio
Purcheuses_sum2_liable
```


```{r}
Purcheuses_sum2_liable <-  left_join(Purcheuses_sum2_liable,Socio, by = "lamas_code" )
```
```{r}
```


```{r}
Purcheuses_sum2_liable
pos_Apt_model_socio <- glm(apartment_count ~familes.with.kids.allowance + Families.with.more.than.4.kids + people.with.general.disability + elederly + kids.with.disabilities + x2019_cluster,
data = Purcheuses_sum2_liable, family = poisson)
summary(pos_Apt_model_socio)

# Predicted values
predicted <- predict(pos_Apt_model_socio, type = "response")

# Actual values
actual <- Purcheuses_sum2_liable$apartment_count

# Compute RMSE
rmse <- sqrt(mean((predicted - actual)^2))

# Compute MAE
mae <- mean(abs(predicted - actual))

# Compute SD of residuals
residuals <- actual - predicted
sd_resid <- sd(residuals)

# Print results
cat("RMSE:", rmse, "\n")
cat("MAE:", mae, "\n")
cat("SD of Residuals:", sd_resid, "\n")
```

```{r}
library(MASS)

# Initial model
initial_model <- glm(apartment_count ~ familes.with.kids.allowance + Families.with.more.than.4.kids + people.with.general.disability + elederly + kids.with.disabilities + x2019_cluster,
                     data = Purcheuses_sum2_liable, family = poisson)

# Perform stepwise regression
stepwise_model <- stepAIC(initial_model, direction = "both")

# Summarize the final model
summary(stepwise_model)

# Predicted values from the final model
predicted <- predict(stepwise_model, type = "response")

# Actual values
actual <- Purcheuses_sum2_liable$apartment_count

# Compute RMSE
rmse <- sqrt(mean((predicted - actual)^2))

# Compute MAE
mae <- mean(abs(predicted - actual))

# Compute SD of residuals
residuals <- actual - predicted
sd_resid <- sd(residuals)

# Print results
cat("RMSE:", rmse, "\n")
cat("MAE:", mae, "\n")
cat("SD of Residuals:", sd_resid, "\n")

```


```{r}
```
```{r}
# Purcheuses_sum2_liable

lm_model_socio <- glm(apartment_count ~ x2019_cluster,
data = Purcheuses_sum2_liable, family = poisson)
summary(lm_model_socio)
```


```{r}
Kneset21_summed <- read.csv("../data/Updated/Kneset21_summed.csv")
liable <- liable %>% 
  clean_names()

# liable
Kneset21_summed <- Kneset21_summed %>% clean_names()
# Kneset21_summed
check_relation <- left_join(liable, Kneset21_summed, by = "lamas_code")
check_relation <- left_join(check_relation,Socio, by = "lamas_code" )
check_relation

lm_model2 <- lm(coalition_support ~familes_with_kids_allowance + families_with_more_than_4_kids + people_with_general_disability + elederly + kids_with_disabilities + x2019_cluster,
data = check_relation)
summary(lm_model2)


```



```{r}
# Initial model (intercept only)
initial_model <- lm(coalition_support ~ 0, data = check_relation)

# Full model (all predictors)
full_model <- lm(coalition_support ~ familes_with_kids_allowance + families_with_more_than_4_kids + people_with_general_disability + elederly + kids_with_disabilities + x2019_cluster, data = check_relation)

# Perform forward stepwise selection
stepwise_model <- step(initial_model, scope = list(lower = initial_model, upper = full_model), direction = "forward")

summary(stepwise_model)
```


